### ISSUE TITLE
[Feature Request] Personal Notes for each question

### ISSUE THREAD

**Issue by highonweb** [neetcode-gh/leetcode#331] opened 2022-06-21 13:53 UTC
It need not be stored in database or server. We can use Local storage to store the notes

**Comment by nraghuveer** [comment] 2022-06-21 20:35
Leetcode has same feature, search for the note symbol on right of problem page, if that works.

**Comment by Ahmad-A0** [comment] 2022-09-04 05:47
This looks like a duplicate of #99, please reopen if this isn't the case.

**Closed by Ahmad-A0** 2022-09-04 05:47 UTC
Labels: enhancement, website-only
