### ISSUE TITLE
Feature Request - allow user can star certain problems

### ISSUE THREAD

**Issue by seungjun-green** [neetcode-gh/leetcode#1012] opened 2022-09-03 17:20 UTC
**Feature Request**

What about adding a new feature that allow user can start certain problems on the neetcdoe website?

When practicing the Blind 75 list, I found some problems that I have to study/solve again. If I can star those problems on the neetcode website, I think it would make the life a little easier for people like me.

Thanks

**Comment by Ahmad-A0** [comment] 2022-09-04 05:48
This seems like a duplicate of #364, please reopen if this isn't the case.

**Closed** 2022-09-04 05:49 UTC
