### ISSUE TITLE
Progress not being shown while signed-in

### ISSUE THREAD

**Issue by Vamsi995** [neetcode-gh/leetcode#845] opened 2022-08-17 12:52 UTC
![image](https://user-images.githubusercontent.com/52487689/185135532-af1b9fd5-bc79-4f4e-8204-2606be2c5588.png)

The progress bars are not working when I sign into the website but when I sign out they are being displayed.

**Comment by Ahmad-A0** [comment] 2022-08-17 13:11
I think this is a duplicate of #580, please reopen if this isn't the case.

**Closed by Ahmad-A0** 2022-08-17 13:11 UTC

**Comment by Vamsi995** [comment] 2022-08-17 13:14
Yes it is the same issue.
